In [1]:
import nltk
print(nltk.__version__)

3.8.1


In [2]:
from nltk import sent_tokenize # 임포트
nltk.download('punkt') # 개행문자, 마침표 등을 데이터셋 다운로드

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LEGION\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [3]:
text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'

In [4]:
# 문장 분리
sents = sent_tokenize(text=text_sample)
sents

['The Matrix is everywhere its all around us, here even in this room.',
 'You can see it out your window or on your television.',
 'You feel it when you go to work, or go to church or pay your taxes.']

In [5]:
print(type(sents), len(sents))

<class 'list'> 3


In [6]:
sents[0]

'The Matrix is everywhere its all around us, here even in this room.'

In [7]:
# 단어 토큰화 : 문장 => 단어 토큰화
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
words

['The',
 'Matrix',
 'is',
 'everywhere',
 'its',
 'all',
 'around',
 'us',
 ',',
 'here',
 'even',
 'in',
 'this',
 'room',
 '.']

In [8]:
len(words)

15

In [9]:
from nltk import word_tokenize, sent_tokenize

# 단어 토큰화 함수
# 파라미터 : text => 하나의 뉴스, 리뷰 등
# 단어 토큰화한 결과 반환
def tokenize_text(text):
    # 문장 분리
    sents = sent_tokenize(text)
    # 단어 분리
    word_tokens = [word_tokenize(sentence) for sentence in sents]
    
    # word_tokens = []
    # for sentence in sents:
    #     word_token = word_tokenize(sentence)
    #     word_tokens.append(word_token)
    return word_tokens

In [10]:
word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [11]:
# 불용어 처리
# 불용어 사전 다운로드
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LEGION\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [12]:
# 영어 기준으로 불용어 확인
# corpus : 말뭉치
print('영어 stop words 개수 : ', len(nltk.corpus.stopwords.words('english')))

영어 stop words 개수 :  179


In [13]:
nltk.corpus.stopwords.words('english')[:20]

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his']

In [14]:
# 불용어 제거
stopwords = nltk.corpus.stopwords.words('english')
print(type(stopwords))
print(stopwords)

<class 'list'>
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 

In [15]:
word_tokens

[['The',
  'Matrix',
  'is',
  'everywhere',
  'its',
  'all',
  'around',
  'us',
  ',',
  'here',
  'even',
  'in',
  'this',
  'room',
  '.'],
 ['You',
  'can',
  'see',
  'it',
  'out',
  'your',
  'window',
  'or',
  'on',
  'your',
  'television',
  '.'],
 ['You',
  'feel',
  'it',
  'when',
  'you',
  'go',
  'to',
  'work',
  ',',
  'or',
  'go',
  'to',
  'church',
  'or',
  'pay',
  'your',
  'taxes',
  '.']]

In [16]:
# word_tokens [] => 반복처리 : 한문장씩 가져와서 처리
# 불용어 제거후 저장할 리스트
all_tokens = []

for sentence in word_tokens: # 한문장씩 반복
    # 문장별 결과를 저장할 리스트
    filtered_words = []
    
    for word in sentence: # 단어별 처리
        # 소문자 변환
        word = word.lower()
        # 불용 단어가 아닌 단어를 찾아서 저장
        if word not in stopwords: # word : 특정단어, stopword : 불용어
            filtered_words.append(word)
    all_tokens.append(filtered_words)

print(all_tokens) # 불용어 처리한 사전
print(word_tokens) # 불용어 처리하지 않은 사전

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [17]:
# 어근 추출
# stemmer, Lemmatizaiton(성능우수, 속도가 느리다)
from nltk import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [18]:
from nltk import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\LEGION\AppData\Roaming\nltk_data...


True

In [19]:
lemma = WordNetLemmatizer()

print(lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a'))
print(lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a'))

amuse amuse amuse
happy happy
fancy fancy


In [20]:
import numpy as np
import pandas as pd

In [21]:
dense = np.array([[3, 0, 1], [0, 2, 0]])
dense

array([[3, 0, 1],
       [0, 2, 0]])

In [22]:
# COO 방식으로 위 데이터 표현
# 0이 아닌 데이터 추출
data = np.array([3,1,2])
# 0이 아닌 데이터의 행 위치와 열 위치를 각각 배열로 생성
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

In [23]:
from scipy import sparse
# sparse module의 coo_matrix() => 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))
sparse_coo

<2x3 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [24]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [25]:
from scipy import sparse

# dense2 = np.array([
#     [0,0,1,0,0,5],
#     [1,4,0,3,2,5],
#     [0,6,0,3,0,0],
#     [2,0,0,0,0,0],
#     [0,0,0,7,0,8],
#     [1,0,0,0,0,0]
# ])

# 0이 아닌 데이터 추출
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])
# 행 위치와 열 위치를 각각 array로 생성
row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

# COO 형식 변환
sparse.coo_matrix((data2, (row_pos,col_pos))).toarray()

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [26]:
row_pos_ind = np.array([0,2,7,9,10,12,13])
sparse.csr_matrix((data2, col_pos, row_pos_ind))

<6x6 sparse matrix of type '<class 'numpy.int32'>'
	with 13 stored elements in Compressed Sparse Row format>

In [27]:
sparse.csr_matrix((data2, col_pos, row_pos_ind)).toarray()

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [28]:
dense3 = np.array([
    [0, 0, 1, 0, 0, 5],
    [1, 4, 0, 3, 2, 5],
    [0, 6, 0, 3, 0, 0],
    [2, 0, 0, 0, 0, 0],
    [0, 0, 0, 7, 0, 8],
    [1, 0, 0, 0, 0, 0]
])

In [29]:
coo = sparse.coo_matrix(dense3)
coo.__sizeof__()

32

In [30]:
coo.toarray().nbytes

144

In [31]:
csr = sparse.csr_matrix(dense3)

In [32]:
print(csr)

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
